#!/usr/bin/awk -f
{
    for (i=1;i<=length($0);i++){
        char=substr($0, i, 1)
        a=b;b=c;c=d;d=char;
        if (a && b && c && d && a!=b && a!=c && a!=d && b!=c && b!=d && c!=d) {print i;a=0;b=0;c=0;d=0; i=99999}
        #print " " a " " b " " c " " d
        }
    for (j=0;j<14;j++){
        window[j]=0
    }
    j=0;
    for (i=1;i<=length($0);i++){
        #print "i1:" i;
        window[j]=substr($0, i, 1)
        j++;
        j%=14;
        doubles=0;
        for (k=0;k<14;k++){
            #print "i2:" i;
            for (t=k+1;t<14;t++){
                #print "i3:" i;
                #print "window[" k "]=" window[k] "    window["t"]="window[t];
                if(window[k]==window[t]){
                    #print "DOUBLES";
                    doubles++;
                }
            }
        }
        #print "doubles:" doubles;
        if (doubles==0) {
            printf i "\n";
            i=9999;k=9999;t=9999;
        }
    }
}
