#!/usr/bin/awk -f
/A X/ {
    a += 4
    b += 3
}

/B Y/ {
    a += 5
    b += 5
}

/C Z/ {
    a += 6
    b += 7
}

/A Y/ {
    a += 8
    b += 4
}

/B Z/ {
    a += 9
    b += 9
}

/C X/ {
    a += 7
    b += 2
}

/A Z/ {
    a += 3
    b += 8
}

/B X/ {
    a += 1
    b += 1
}

/C Y/ {
    a += 2
    b += 6
}

END { print a "\n" b }
