#!/usr/bin/awk -f
BEGIN {
    FS = ""

    for (n = 0; n < 256; n++) { ind[sprintf("%c", n)] = n - 97 }
}

function part_1_hardcoded() {
    for (i = 1; i <= NF; i++) {
        a = b
        b = c
        c = d
        d = $i

        if (\
            a && b && c && d && a != b && a != c && a != d && b != c &&
            b != d &&
            c != d\
        ) {
            print i
            a = 0
            b = 0
            c = 0
            d = 0
            break
        }
    }
}

function part_2_hardcoded() {
    #this is very ugly, but it performs way better then arrays
    for (i = 1; i <= NF; i++) {
        a = b
        b = c
        c = d
        d = e
        e = f
        f = g
        g = h
        h = j
        j = k
        k = l
        l = m
        m = n
        n = o
        o = $i

        if (\
            i >= 14 && a != b && a != c && a != d && a != e && a != f &&
            a != g &&
            a != h &&
            a != j &&
            a != k &&
            a != l &&
            a != m &&
            a != n &&
            a != o &&
            b != c &&
            b != d &&
            b != e &&
            b != f &&
            b != g &&
            b != h &&
            b != j &&
            b != k &&
            b != l &&
            b != m &&
            b != n &&
            b != o &&
            c != d &&
            c != e &&
            c != f &&
            c != g &&
            c != h &&
            c != j &&
            c != k &&
            c != l &&
            c != m &&
            c != n &&
            c != o &&
            d != e &&
            d != f &&
            d != g &&
            d != h &&
            d != j &&
            d != k &&
            d != l &&
            d != m &&
            d != n &&
            d != o &&
            e != f &&
            e != g &&
            e != h &&
            e != j &&
            e != k &&
            e != l &&
            e != m &&
            e != n &&
            e != o &&
            f != g &&
            f != h &&
            f != j &&
            f != k &&
            f != l &&
            f != m &&
            f != n &&
            f != o &&
            g != h &&
            g != j &&
            g != k &&
            g != l &&
            g != m &&
            g != n &&
            g != o &&
            h != j &&
            h != k &&
            h != l &&
            h != m &&
            h != n &&
            h != o &&
            j != k &&
            j != l &&
            j != m &&
            j != n &&
            j != o &&
            k != l &&
            k != m &&
            k != n &&
            k != o &&
            l != m &&
            l != n &&
            l != o &&
            m != n &&
            m != o &&
            n != o\
        ) {
            print i
            break
        }
    }
}

{
    part_1_hardcoded()

    part_2_hardcoded()
}
