#!/usr/bin/awk -f
BEGIN {
    mx["R"] = 1
    mx["L"] = -1
    mx["U"] = 0
    mx["D"] = 0
    my["R"] = 0
    my["L"] = 0
    my["U"] = 1
    my["D"] = -1

    Rx[0][0] = 0
    Rx[1][0] = 0
    Rx[-1][0] = 0
    Rx[0][1] = 0
    Rx[0][-1] = 0
    Rx[2][0] = 1
    Rx[-2][0] = -1
    Rx[0][2] = 0
    Rx[0][-2] = 0

    Rx[2][1] = 1
    Rx[2][-1] = 1
    Rx[-2][1] = -1
    Rx[-2][-1] = -1
    Rx[1][2] = 1
    Rx[-1][2] = -1
    Rx[1][-2] = 1
    Rx[-1][-2] = -1

    Rx[2][2] = 1
    Rx[-2][2] = -1
    Rx[2][-2] = 1
    Rx[-2][-2] = -1

    Ry[0][0] = 0
    Ry[1][0] = 0
    Ry[-1][0] = 0
    Ry[0][1] = 0
    Ry[0][-1] = 0
    Ry[2][0] = 0
    Ry[-2][0] = 0
    Ry[0][2] = 1
    Ry[0][-2] = -1

    Ry[2][1] = 1
    Ry[2][-1] = -1
    Ry[-2][1] = 1
    Ry[-2][-1] = -1
    Ry[1][2] = 1
    Ry[-1][2] = 1
    Ry[1][-2] = -1
    Ry[-1][-2] = -1

    Ry[2][2] = 1
    Ry[-2][2] = 1
    Ry[2][-2] = -1
    Ry[-2][-2] = -1

    for (i = 0; i <= 9; i++) {
        rx[i] = 0
        ry[i] = 0
    }
}

{
    for (i = 0; i < $2; i++) {
        rx[0] += mx[$1]
        ry[0] += my[$1]
        #print $1 " j=0 rx[0]=" rx[0] " ry[0]=" ry[0]
        for (j = 1; j <= 9; j++) {
            dx = rx[j - 1] - rx[j]
            dy = ry[j - 1] - ry[j]
            rx[j] += Rx[dx][dy]
            ry[j] += Ry[dx][dy]
            #print $1 " j=" j " rx["j-1"]=" rx[j-1] " ry["j-1"]=" ry[j-1] " rx["j"]=" rx[j] " ry["j"]=" ry[j]
        }

        visited[rx[9]][ry[9]] = 1
        visiteda[rx[1]][ry[1]] = 1
        #print $1 " xh=" xh " yh=" yh " xt=" xt " yt=" yt " dx=" dx " dy=" dy
    }
}

END {
    for (x in visited) {
        for (y in visited[x]) {
            if (visited[x][y] == 1) { c++ }
        }
    }

    for (x in visiteda) {
        for (y in visiteda[x]) {
            if (visiteda[x][y] == 1) { a++ }
        }
    }

    print a "\n" c
}
