#!/usr/bin/awk -f
BEGIN { FS = "[ :]" }

function maximum_geodes_opened(id, time_left, ore, cla, obs, geo, ore_r, cla_r, obs_r, geo_r, str) {
    #printf( "considering %50s  %3d",str, geo)
    #print ""
    if (time_left <= 0) {
        if (geo > most_geodes) {
            most_geodes = geo
            print str " " geo
        }

        return
    }

    #build geo
    if (ore >= blueprint[id][3][0] && obs >= blueprint[id][3][2]) {
        #print "building geode robot"
        maximum_geodes_opened(\
            id,
            time_left - 1,
            ore + ore_r - blueprint[id][3][0],
            cla + cla_r,
            obs + obs_r - blueprint[id][3][2],
            geo + geo_r,
            ore_r,
            cla_r,
            obs_r,
            geo_r + 1,
            str ":G"\
        )
    }

    #build obs
    if (ore >= blueprint[id][2][0] && cla >= blueprint[id][2][1]) {
        #print "building obsidian robot"
        maximum_geodes_opened(\
            id,
            time_left - 1,
            ore + ore_r - blueprint[id][2][0],
            cla + cla_r - blueprint[id][2][1],
            obs + obs_r,
            geo + geo_r,
            ore_r,
            cla_r,
            obs_r + 1,
            geo_r,
            str ":O"\
        )
    }

    #build cla
    if (ore >= blueprint[id][1][0]) {
        #print "building clay robot"
        maximum_geodes_opened(\
            id,
            time_left - 1,
            ore + ore_r - blueprint[id][1][0],
            cla + cla_r,
            obs + obs_r,
            geo + geo_r,
            ore_r,
            cla_r + 1,
            obs_r,
            geo_r,
            str ":C"\
        )
    }

    #build ore
    if (ore >= blueprint[id][0][0]) {
        #print "building ore robot"
        maximum_geodes_opened(\
            id,
            time_left - 1,
            ore + ore_r - blueprint[id][0][0],
            cla + cla_r,
            obs + obs_r,
            geo + geo_r,
            ore_r + 1,
            cla_r,
            obs_r,
            geo_r,
            str ":O"\
        )
    }

    #do nothing
    maximum_geodes_opened(\
        id,
        time_left - 1,
        ore + ore_r,
        cla + cla_r,
        obs + obs_r,
        geo + geo_r,
        ore_r,
        cla_r,
        obs_r,
        geo_r,
        str ":."\
    )
}

function print_blueprint(id) {
    print\
        "ID: " id ", ore costs ore:" blueprint[id][0][0] ", clay cost ore:"\
            blueprint[id][1][0]\
            ", obsidian cost ore:"\
            blueprint[id][2][0]\
            ", obsidian cost clay:"\
            blueprint[id][2][1]\
            ", goede cost ore:"\
            blueprint[id][3][0]\
            ", geode cost obsidian:"\
            blueprint[id][3][2]
}

function compute_quality_level(id, ORE_cost_ore, CLA_cost_ore, OBS_cost_ore, OBS_cost_clay, GEO_cost_ore, GEO_cost_obs) {
    id = int(id)
    blueprint[id][0][0] = int(ORE_cost_ore)
    blueprint[id][1][0] = int(CLA_cost_ore)
    blueprint[id][2][0] = int(OBS_cost_ore)
    blueprint[id][2][1] = int(OBS_cost_clay)
    blueprint[id][3][0] = int(GEO_cost_ore)
    blueprint[id][3][2] = int(GEO_cost_obs)
    print_blueprint(id)
    most_geodes = 0
    maximum_geodes_opened(id, 24, 0, 0, 0, 0, 1, 0, 0, 0, "")
    print "max return geodes " most_geodes
    return id * most_geodes
}

{
    print $0
    print ""
    total_quality += compute_quality_level($2, $8, $14, $20, $23, $29, $32)
    print ""
}

END { print "total quality is " total_quality }
