#!/usr/bin/awk -f
{
    line++
    len=length($0)
    for(i=1;i<=len;i++){
        height[line-1][i-1]=substr($0,i,1)
    }
}
END{
    #print "visibility from top"
    for(i=0;i<len;i++){
        h=-1
        for(l=0;l<line;l++){
            if(height[l][i]>h){
                h=height[l][i]
                vt[l][i]=1
                #print l " " i
            }
        }
    }
    #print "visibility from bot"
    for(i=0;i<len;i++){
        h=-1
        for(l=line-1;l>=0;l--){
            if(height[l][i]>h){
                h=height[l][i]
                vb[l][i]=1
                #print l " " i
            }
        }
    }
    #print "visibility from left"
    for(l=0;l<line;l++){
        h=-1
        for(i=0;i<len;i++){
            if(height[l][i]>h){
                h=height[l][i]
                vl[l][i]=1
                #print l " " i
            }
        }
    }
    #print "visibility from right"
    for(l=0;l<line;l++){
        h=-1
        for(i=len-1;i>=0;i--){
            if(height[l][i]>h){
                h=height[l][i]
                vr[l][i]=1
                #print l " " i
            }
            if(vr[l][i]==1 || vl[l][i]==1 || vt[l][i]==1 || vb[l][i]==1){
                somewhere++
            }
        }
    }
    print somewhere
    high_score=0
    for(l=0;l<line;l++){
        for(i=0;i<len;i++){
            a=0
            b=0
            c=0
            d=0
            #print "finding scenic score for coordinate " l " " i
            for(lv=l-1;lv>=0;lv--){
                a++
                #print "above " lv " " i " view ok " a
                if(height[lv][i]>=height[l][i]){
                    lv=-1
                }
            }
            for(lv=l+1;lv<line;lv++){
                b++
                #print "below " lv " " i " view ok " a
                if(height[lv][i]>=height[l][i]){
                    lv=99999
                }
            }
            for(iv=i-1;iv>=0;iv--){
                c++
                #print "left " lv " " i " view ok " a
                if(height[l][iv]>=height[l][i]){
                    iv=-i
                }
            }
            for(iv=i+1;iv<len;iv++){
                d++
                #print "right " lv " " i " view ok " a
                if(height[l][iv]>=height[l][i]){
                    iv=99999
                }
            }
            score=a*b*c*d
            if(score>high_score){
                high_score=score
            }
        }
    }
    print high_score
}
