#!/usr/bin/awk -f
{
    line++
    heighest_left = -1
    heighest_right = -1
    leng =length($0)
    for(i=1;i<=length($0);i++){
        height[line][i]=substr($0,i,1)
        #print "prev highest top at " i " " highest_top[i-1] " comparing " height[line][i]
        if(!highest_top[i-1] || highest_top[i-1]<height[line][i]){
            highest_top[i-1]=height[line][i]
            visible_top[line][i]=1
            #print "new highest top at " i " " highest_top[i-1]
        }
        visible_bot[line][i]=1
        #print "prev highest bot at " i " " highest_bot[i-1] " comparing " height[line][i]
        for(l in visible_bot){
            if(l<line && height[l][i]<=height[line][i]){
                visible_bot[l][i]=0
                #print "removing " l " " i
            }
        }

        if (height[line][i]>heighest_left){
            heighest_left=height[line][i]
            visible_left[line][i]=1
        }
    }
    for(i=length($0);i>=1;i--){
        if (height[line][i]>heighest_right){
            heighest_right=height[line][i]
            visible_right[line][i]=1
        }
    }
    #print $0
    #print ""
    #print "visibility from bot"
    #print ""
    #for(l in visible_bot){
    #    for(i in visible_bot[l]){
    #        if(visible_bot[l][i]==1){
    #           print l " " i
    #        }
    #    }
    #}
    #print ""
}
END{
    print "visibility from top"
    print ""
    for(l in visible_top){
        for(i in visible_top[l]){
            if(visible_top[l][i]==1){
                print l " " i
            }
        }
    }
    print "visibility from bot"
    print ""
    for(l in visible_bot){
        for(i in visible_bot[l]){
            if(visible_bot[l][i]==1){
                print l " " i
            }
        }
    }
    print "visibility from left"
    print ""
    for(l in visible_left){
        for(i in visible_left[l]){
            if(visible_left[l][i]==1){
                print l " " i
            }
        }
    }
    print "visibility from right"
    print ""
    for(l in visible_right){
        for(i in visible_right[l]){
            if(visible_right[l][i]==1){
                print l " " i
            }
        }
    }
    for(l=1;l<=leng;l++){
        for(i=1;i<=leng;i++){
            if( visible_top[l][i]==1){
                printf " v "
            } else{
                printf "   "
            }
        }
        print ""
        for(i=1;i<=leng;i++){
            visible=0
            if( visible_left[l][i]==1 && visible_right[l][i]==1){
                printf ">" height[l][i] "<"
            } else if( visible_left[l][i]==1){
                printf ">" height[l][i] " "
            } else if (visible_right[l][i]==1){
                printf " " height[l][i] "<"
            }else{
                printf " " height[l][i] " "
            }
        }
        print ""
        for(i=1;i<=leng;i++){
            if( visible_bot[l][i]==1){
                printf " ^ "
            } else{
                printf "   "
            }
        }
        print ""

        for(i=1;i<=leng;i++){
        if(visible_right[l][i]==1 ||
            visible_left[l][i]==1 ||
            visible_bot[l][i]==1 ||
            visible_top[l][i]==1){
                visible_somewhere++
       }
       }
    }
    print "visible somewhere " visible_somewhere
    print "line" line
    print "leng" leng
}
