#!/usr/bin/awk -f
BEGIN{line=0;for(n=0;n<256;n++)ord[sprintf("%c",n)]=n-38*(n<91)-96*(n>90)}
{
    for(i=1;i<=length($0)/2;i++){
        for(j=length($0)/2+1;j<=length($0);j++){
            #print "comp " substr($0,i,1) " " substr($0,j,1)
            if( substr($0,i,1) == substr($0,j,1)){
                t+= ord[substr($0,i,1)]
                i=9999
            }
        }
    }
    if(line==0){
        line0=$0 
    }
    else if(line==1){
        line1=$0 
    }
    else{
         #print line ":  " line0 "    " line1 "    " $0
    for(i=1;i<=length(line0);i++){
        for(j=1;j<=length(line1);j++){
            #print "comp " substr(line0,i,1) " " substr(line1,j,1)
            if( substr(line0,i,1) == substr(line1,j,1)){
                #print "candidate" substr(line0,i,1)
                for(k=1;k<=length($0);k++){
                    #print "comp " substr(line0,i,1) " " substr($0,j,1)
                    if( substr(line0,i,1) == substr($0,k,1)){
                        #print substr(line0,i,1)
                        s+= ord[substr(line0,i,1)]
                        i=9999
                    }
                }
            }
        }
    }
}
line++;line%=3;
}
END{print t "\n" s}

