#!/usr/bin/awk -f
/A X/{c+=4; d+=3}
/B Y/{c+=5; d+=5}
/C Z/{c+=6; d+=7}
/A Y/{c+=8; d+=4}
/B Z/{c+=9; d+=9}
/C X/{c+=7; d+=2}
/A Z/{c+=3; d+=8}
/B X/{c+=1; d+=1}
/C Y/{c+=2; d+=6}
END{print c "\n" d}
