#!/usr/bin/awk -f
BEGIN{
    xh=0
    yh=0
    xt=0
    yt=0
    mx["R"]=1
    mx["L"]=-1
    mx["U"]=0
    mx["D"]=0
    my["R"]=0
    my["L"]=0
    my["U"]=1
    my["D"]=-1

    Rx[0][0]=0
    Rx[1][0]=0
    Rx[-1][0]=0
    Rx[0][1]=0
    Rx[0][-1]=0
    Rx[2][0]=1
    Rx[-2][0]=-1
    Rx[0][2]=0
    Rx[0][-2]=0

    Rx[2][1]=1
    Rx[2][-1]=1
    Rx[-2][1]=-1
    Rx[-2][-1]=-1
    Rx[1][2]=1
    Rx[-1][2]=-1
    Rx[1][-2]=1
    Rx[-1][-2]=-1

    Ry[0][0]=0
    Ry[1][0]=0
    Ry[-1][0]=0
    Ry[0][1]=0
    Ry[0][-1]=0
    Ry[2][0]=0
    Ry[-2][0]=0
    Ry[0][2]=1
    Ry[0][-2]=-1

    Ry[2][1]=1
    Ry[2][-1]=-1
    Ry[-2][1]=1
    Ry[-2][-1]=-1
    Ry[1][2]=1
    Ry[-1][2]=1
    Ry[1][-2]=-1
    Ry[-1][-2]=-1
}
{
    for(i=0;i<$2;i++){
        xh+=mx[$1]
        yh+=my[$1]
        dx=xh-xt
        dy=yh-yt
        xt+=Rx[dx][dy]
        yt+=Ry[dx][dy]
        visited[xt][yt]=1
        #print $1 " xh=" xh " yh=" yh " xt=" xt " yt=" yt " dx=" dx " dy=" dy
    }
}
END{
    for(x in visited){
        for(y in visited[x]){
            if(visited[x][y]==1){
                c++
            }
        }
    }
    print c
}
